my_proj/src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

my_proj/src/bot/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
#from django.views.generic.edit import ProcessFormView
from . import views

urlpatterns = [
	url(r'^process/',views.process,name="process"),
    url(r'^search', TemplateView.as_view(template_name= "bot/main.html"), name="bot"),
    url(r'^results', TemplateView.as_view(template_name= "bot/results.html"), name="bot"),
    url(r'^index', TemplateView.as_view(template_name= "bot/index.html"), name="bot"),
    url(r'^new_base', TemplateView.as_view(template_name= "bot/new_base.html"), name="bot"),

    ]

my_proj/src/my_proj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import bot.urls
from . import views

urlpatterns = [
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
]

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        url(r'^bot/',include(bot.urls, namespace='bot')),
    ]

my_proj/src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

my_proj/src/bot/files/models.py
from pymongo import MongoClient, DESCENDING,ASCENDING
from datetime import datetime
from bson import json_util
import re
import json

def connect_to_db(collection=False) :
	connection = MongoClient('localhost',27017)
	db = connection['myntra']
	try :
		if collection :
			return db.myntraitems
		return db

	except Exception as e :
		pass


def insert(input_dict) :
	table = connect_to_db(collection = True)
	table.insert({'crawled_at':datetime.utcnow(),\
		'id':input_dict.get('id',None),\
		'title':input_dict.get('title',None),\
		'brand':input_dict.get('brand',None),\
		'sizes':input_dict.get('sizes',None),\
		'original_price':input_dict.get('original_price',None),\
		'discounted_price':input_dict.get('discounted_price',None)
		})

def fetch_by_title(title,_as=None):
	print "Title:",title
	result=[]
	table=connect_to_db(collection=True)
	regex='.*'+title+'.*'
	for row in table.find({"title": re.compile(regex,re.IGNORECASE)}).sort('id',ASCENDING):
		result.append(row)
	if _as =='json':
		return json.dumps({title:result},default=json_util.default)
	return result

my_proj/src/bot/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

my_proj/src/bot/forms.py
from django import forms

class BotForm(forms.Form):
    search_text = forms.CharField(max_length=100)

my_proj/src/bot/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import BotForm
import time
from bot.files import *
# Create your views here.

def process(request):
	results=[]
	if request.method == 'POST':
		myform = BotForm(request.POST)
		if myform.is_valid():
			text=myform.cleaned_data['search_text']
			print(text)
			crawler_machine(text)
			time.sleep(100)
			results=fetch_by_title(text)
			#print(result)
			#print("hi")
		#print("hello")
	return render(request,"bot/results.html",{'results':results})

my_proj/src/bot/templates/bot/index.html
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Bootstrap Chat Box Example</title>
    <link rel="stylesheet" href="{% static 'chat-box/assets/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'chat-box/assets/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'chat-box/assets/css/style.css' %}">

</head>
<body>


    <div class="container">
        <div class="row pad-top pad-bottom">


            <div class=" col-lg-4 col-md-4 col-sm-4">
                <div class="chat-box-div">
                    <div class="chat-box-head">
                        GROUP CHAT HISTORY
                            <div class="btn-group pull-right">
                                <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <span class="fa fa-cogs"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#"><span class="fa fa-map-marker"></span>&nbsp;Invisible</a></li>
                                    <li><a href="#"><span class="fa fa-comments-o"></span>&nbsp;Online</a></li>
                                    <li><a href="#"><span class="fa fa-lock"></span>&nbsp;Busy</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#"><span class="fa fa-circle-o-notch"></span>&nbsp;Logout</a></li>
                                </ul>
                            </div>
                    </div>
                    <div class="panel-body chat-box-main">
                        <div class="chat-box-left">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </div>
                        <div class="chat-box-name-left">
                            <img src="{% static 'chat-box/assets/img/user.png' %}" alt="bootstrap Chat box user image" class="img-circle" />
                            -  Justine Goliyad
                        </div>
                        <hr class="hr-clas" />
                        <div class="chat-box-right">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </div>
                        <div class="chat-box-name-right">
                            <img src="chat-box/assets/img/user.gif" alt="bootstrap Chat box user image" class="img-circle" />
                            - Romin Royeelin
                        </div>
                        <hr class="hr-clas" />
                        <div class="chat-box-left">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </div>
                        <div class="chat-box-name-left">
                            <img src="chat-box/assets/img/user.png" alt="bootstrap Chat box user image" class="img-circle" />
                            -  Justine Goliyad
                        </div>
                        <hr class="hr-clas" />
                        <div class="chat-box-right">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                           Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        </div>
                        <div class="chat-box-name-right">
                            <img src="chat-box/assets/img/user.gif" alt="bootstrap Chat box user image" class="img-circle" />
                            - Romin Royeelin
                        </div>
                        <hr class="hr-clas" />
                    </div>
                    <div class="chat-box-footer">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Enter Text Here...">
                            <span class="input-group-btn">
                                <button class="btn btn-info" type="button">SEND</button>
                            </span>
                        </div>
                    </div>

                </div>

            </div>
            
            </div>
           

            </div>
        </div>
    </div>

    <!-- USING SCRIPTS BELOW TO REDUCE THE LOAD TIME -->
    <!-- CORE JQUERY SCRIPTS FILE -->
    <script src="assets/js/jquery-1.11.1.js"></script>
    <!-- CORE BOOTSTRAP SCRIPTS  FILE -->
    <script src="assets/js/bootstrap.js"></script>
</body>

</html>

my_proj/src/bot/templates/bot/main.html
<!DOCTYPE html>
<html>
<head>
<title>HTML Frames</title>
</head>


<frameset rows="55,*" frameborder="0" border="0" framespacing="0">
  <frame name="topNav" src="new_base.html">
<frameset cols="35%,65%" frameborder="0" border="0" framespacing="0">
	<frame name="menu" src="index.html" marginheight="0" marginwidth="0" scrolling="auto">
	<frame name="content" src="results.html" marginheight="0" marginwidth="0" scrolling="auto" noresize>

<noframes>
<p>This section (everything between the 'noframes' tags) will only be displayed if the users' browser doesn't support frames. You can provide a link to a non-frames version of the website here. Feel free to use HTML tags within this section.</p>
</noframes>

</frameset>
</frameset>
<!--<frameset cols="35%,65%">

   <frame name="left" src="index.html" />
   <frame name="right" src="results.html" />
   <noframes>
   <body>
      Your browser does not support frames.
   </body>
   </noframes>
</frameset> -->

</html>

my_proj/src/bot/templates/bot/new_base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}

  <head>
    <style>
      div.custom
      {
        padding: 5px 50px 5px 50px;
      }
      div.messagebox
      {
        background-color: lightblue;
        padding: 10px 10px 10px 10px;
        border-radius: 25px;
      }
      div.ownmessage
      {
        width: 1000px;
        background-color: lightgreen;
        padding: 10px 10px 10px 10px;
        border-radius: 25px;
      }
      div.friendmessage
      {
        width: 1000px;
        background-color: lightgrey;
        padding: 10px 10px 10px 10px;
        border-radius: 25px;
      }
      .img-circle 
      {
        border-radius: 50%;
      }
    </style>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>

                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}


    {

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
     <br>
     <br>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

my_proj/src/bot/templates/bot/results.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900|Varela+Round" rel="stylesheet"/>
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Abel|Satisfy' rel='stylesheet' type='text/css' />
<!--<link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}">-->
<link rel="stylesheet" href="{% static 'chat-box/assets/css/stylesearch.css' %}">
  <!-- Compiled and minified CSS -->
  <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
      <style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>


</head>
<body>
  

 
      <!--<form class="form" action="" method="post" name="new-service" enctype=multipart/form-data>
      <div class="control-group">
          
          <div class="controls">
               <input id="Search" name="Search" type="text" placeholder="Search.. eg: moto g" class="form-control input-xlarge search-query center-display" required="" length="100">
          </div>
     </div>
      
      </form>
    -->
    <!--<form class="col s12">
      <div class="row">
        <div class="input-field col s3 m6">
          <input id="first_name" type="text" class="validate">
          <label for="first_name">Search</label>
        </div>
      </div>
    </form>-->
    <br><br>
    <form id="search-form_3" action="{% url "bot:process" %}" method="POST">
    {% csrf_token %}
    <input type="text" class="search_3" name="search_text"/>
  <input type="submit" class="submit_3" value="Search" />
</form>
<br><br>
      <table class="striped bordered" >
        <thead>
          <tr>
            <th data-field="Id"> ID </th>
              <th data-field="title">Title</th>
              <th data-field="brand">Brand</th>
              <th data-field="oprice">Original Price</th>
              <th data-field="dprice">Discounted Price </th>
          </tr>
        </thead>

        <tbody>
          {% for r in results %}
          <tr>
            <td>{{r.id}}</td>
            <td>{{r.title}}</td>
            <td>{{r.brand}}</td>
            <td>{{r.original_price}}</td>
            <td>{{r.discounted_price}}</td>
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
</body>
</html>
            

my_proj/src/bot/templates/bot/search.html
<!DOCTYPE html>
<html>
<head>
<title>Design search Button - Demo Preview</title>
<meta content="noindex, nofollow" name="robots">
<!-- Include CSS File Here-->
<link href="style.css" rel="stylesheet">
</head>
<body>
<div id="main">
<div id="first">

<hr>

    
	
    <form id="search-form_3">
  <input type="text" class="search_3"/>
  <input type="submit" class="submit_3" value="Search" />
</form>
    
  
     
    
	
</body>
</html>